INSERT INTO ADDRESS (ID, ADDITIONALINFO, STREET, CITYZIP) VALUES (1, '304 st. th', 'Vestervang', 6091);
INSERT INTO ADDRESS (ID, ADDITIONALINFO, STREET, CITYZIP) VALUES (2, '21', 'Østerløkke', 6000);
INSERT INTO ADDRESS (ID, ADDITIONALINFO, STREET, CITYZIP) VALUES (3, '52', 'Main street', 2800);
INSERT INTO ADDRESS (ID, ADDITIONALINFO, STREET, CITYZIP) VALUES (4, '72 st', 'Nordvej', 2400);
INSERT INTO ADDRESS (ID, ADDITIONALINFO, STREET, CITYZIP) VALUES (5, '31', 'hovedgaden', 8210);

INSERT INTO COMPANY (ID, CVR, DESCRIPTION, MARKETVALUE, NAME, NUMEMPLOYEES) VALUES(1, 123456, 'Nyt firma', 9000, 'Mærsk', 25000);
INSERT INTO COMPANY (ID, CVR, DESCRIPTION, MARKETVALUE, NAME, NUMEMPLOYEES) VALUES(2, 123426, 'Nyt firma', 8000, 'Novo', 1000);
INSERT INTO COMPANY (ID, CVR, DESCRIPTION, MARKETVALUE, NAME, NUMEMPLOYEES) VALUES(3, 523456, 'Nyt firma', 5000, 'Vestas', 40);
INSERT INTO COMPANY (ID, CVR, DESCRIPTION, MARKETVALUE, NAME, NUMEMPLOYEES) VALUES(4, 823456, 'Nyt firma', 4000, 'Lenovo', 20);